/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author asus4
 */
public class FrameBeranda extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameBeranda.class.getName());

    /**
     * Creates new form FrameBeranda
     */
    public FrameBeranda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnKeluar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btDurian = new javax.swing.JLabel();
        btMangga = new javax.swing.JLabel();
        btJeruk = new javax.swing.JLabel();
        btMelon = new javax.swing.JLabel();
        btKiwi = new javax.swing.JLabel();
        btSemangka = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jButton4.setText("jButton4");

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 650));

        jPanel1.setMaximumSize(new java.awt.Dimension(498, 640));
        jPanel1.setMinimumSize(new java.awt.Dimension(498, 640));
        jPanel1.setPreferredSize(new java.awt.Dimension(498, 640));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(24, 58, 92));
        jLabel1.setText("DATA BUAH");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        btnKeluar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKeluar.setForeground(new java.awt.Color(24, 58, 92));
        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tk2teamone/icon/btnKeluar.png"))); // NOI18N
        btnKeluar.setText("Keluar Aplikasi ");
        btnKeluar.addActionListener(this::btnKeluarActionPerformed);
        jPanel1.add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 570, 160, 40));

        jPanel2.setMaximumSize(new java.awt.Dimension(448, 383));
        jPanel2.setMinimumSize(new java.awt.Dimension(448, 383));
        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(448, 383));
        jPanel2.setLayout(new java.awt.GridLayout(2, 3));

        btDurian.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btDurian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tk2teamone/icon/btnDurian.png"))); // NOI18N
        btDurian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btDurianMouseClicked(evt);
            }
        });
        jPanel2.add(btDurian);

        btMangga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btMangga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tk2teamone/icon/btnMangga.png"))); // NOI18N
        btMangga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btManggaMouseClicked(evt);
            }
        });
        jPanel2.add(btMangga);

        btJeruk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btJeruk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tk2teamone/icon/btnJeruk.png"))); // NOI18N
        btJeruk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btJerukMouseClicked(evt);
            }
        });
        jPanel2.add(btJeruk);

        btMelon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btMelon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tk2teamone/icon/btnMelon.png"))); // NOI18N
        btMelon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btMelonMouseClicked(evt);
            }
        });
        jPanel2.add(btMelon);

        btKiwi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btKiwi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tk2teamone/icon/btnKiwi.png"))); // NOI18N
        btKiwi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btKiwiMouseClicked(evt);
            }
        });
        jPanel2.add(btKiwi);

        btSemangka.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btSemangka.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tk2teamone/icon/btnSemangka.png"))); // NOI18N
        btSemangka.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btSemangkaMouseClicked(evt);
            }
        });
        jPanel2.add(btSemangka);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 480, 410));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tk2teamone/icon/text.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 110, 100));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(24, 58, 92));
        jLabel5.setText("dikelola");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(24, 58, 92));
        jLabel4.setText("Pilih jenis buah yang ingin ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 210, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tk2teamone/icon/bg.png"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(498, 640));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btDurianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDurianMouseClicked
        // TODO add your handling code here:
        new FrameDurian().setVisible(true);
        dispose();
    }//GEN-LAST:event_btDurianMouseClicked

    private void btManggaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btManggaMouseClicked
        // TODO add your handling code here:
        new FrameMangga().setVisible(true);
        dispose();
    }//GEN-LAST:event_btManggaMouseClicked

    private void btJerukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btJerukMouseClicked
        // TODO add your handling code here:
        new FrameJeruk().setVisible(true);
        dispose();
    }//GEN-LAST:event_btJerukMouseClicked

    private void btMelonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btMelonMouseClicked
        // TODO add your handling code here:
        new FrameMelon().setVisible(true);
        dispose();
    }//GEN-LAST:event_btMelonMouseClicked

    private void btKiwiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btKiwiMouseClicked
        // TODO add your handling code here:
        new FrameKiwi().setVisible(true);
        dispose();
    }//GEN-LAST:event_btKiwiMouseClicked

    private void btSemangkaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSemangkaMouseClicked
        // TODO add your handling code here:
        new FrameSemangka().setVisible(true);
        dispose();
    }//GEN-LAST:event_btSemangkaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
            UIManager.put("Button.arc", 15);
            UIManager.put("Button.Borderwidth", 0);
            UIManager.put("TextComponent.arc", 15);
        } catch (UnsupportedLookAndFeelException unsupportedLookAndFeelException) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrameBeranda().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btDurian;
    private javax.swing.JLabel btJeruk;
    private javax.swing.JLabel btKiwi;
    private javax.swing.JLabel btMangga;
    private javax.swing.JLabel btMelon;
    private javax.swing.JLabel btSemangka;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
